import os
import datetime

from pathlib import Path
from bytele.game.common.map.game_board import GameBoard
from bytele.game.utils.ldtk_helpers import map_data_from_ldtk_file


MAP_DATA_FILEPATH = Path('game', 'map_data.py')


def compile_map_data():
    """
    saves the parsed LDtk map size and entity locations as Python dicts
    so that they can be embedded into the launcher

    this means that any time the LDtk file is changed and the launcher
    is being redistributed, this script should be run
    """
    locations, map_size = map_data_from_ldtk_file('map.ldtk')
    locations_dict = GameBoard.locations_to_json_dict(locations)
    use_precompiled_map = os.getenv('CLIENT_PACKAGE_BUILD') == 'true'
    with MAP_DATA_FILEPATH.open('w') as map_file:
        header = f'# generated by {Path(__file__).name} on {datetime.datetime.now(datetime.UTC)}'
        use_precompiled_map_line = f'USE_PRECOMPILED_MAP = {use_precompiled_map}'
        map_size_line = f'MAP_SIZE = {map_size.to_json()}'
        map_dict_line = f'MAP_DICT = {locations_dict}'
        combined = '\n'.join([
            header,
            use_precompiled_map_line,
            map_size_line,
            map_dict_line,
        ])
        map_file.writelines(combined)
        print(header)
        print(use_precompiled_map_line)
        print(map_size_line)
        print(map_dict_line[:50], '(line truncated)')
        print(f'Saved to {MAP_DATA_FILEPATH.resolve()}')


if __name__ == '__main__':
    compile_map_data()
