name: Build and run a game

on:
  push:
    paths:
      - 'game/**'
      - 'server/**'
      - 'visualizer/**'
      - 'wrapper/**'
      - 'build.*'
      - 'map.ldtk'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: .\build.bat
    - name: Build (*nix)
      if: runner.os != 'Windows'
      run: ./build.sh
    - name: Generate map
      run: python launcher.pyz g
    - name: Run game
      run: python launcher.pyz r
